{{- if .Values.adminWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "truemark.fullname" . }}-admin-web
  labels:
    app: truemark-admin-web
spec:
  replicas: {{ .Values.adminWeb.replicaCount }}
  selector:
    matchLabels:
      app: truemark-admin-web
  template:
    metadata:
      labels:
        app: truemark-admin-web
    spec:
      containers:
        - name: admin-web
          image: "{{ .Values.adminWeb.image.repository }}:{{ .Values.adminWeb.image.tag }}"
          imagePullPolicy: {{ .Values.adminWeb.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range $k, $v := .Values.adminWeb.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.adminWeb.resources | nindent 12 }}
{{- end }}
