export enum TenantStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DISABLED = 'DISABLED',
}

export enum DomainStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  DISABLED = 'DISABLED',
}

export enum DeploymentType {
  SAAS = 'SAAS',
  DEDICATED_CLOUD = 'DEDICATED_CLOUD',
  CUSTOMER_CLOUD = 'CUSTOMER_CLOUD',
  ON_PREM = 'ON_PREM',
  HYBRID = 'HYBRID',
}

export enum LifecycleStatus {
  DRAFT = 'DRAFT',
  REGISTERED = 'REGISTERED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  REVOKED = 'REVOKED',
  RECALLED = 'RECALLED',
  DISCONTINUED = 'DISCONTINUED',
  RETIRED = 'RETIRED',
}

export enum VerificationResult {
  VERIFIED = 'VERIFIED',
  REVERIFIED = 'REVERIFIED',
  SUSPICIOUS = 'SUSPICIOUS',
  POSSIBLE_CLONE = 'POSSIBLE_CLONE',
  POSSIBLE_COUNTERFEIT = 'POSSIBLE_COUNTERFEIT',
  CONFIRMED_COUNTERFEIT = 'CONFIRMED_COUNTERFEIT',
  INVALID_QR = 'INVALID_QR',
  UNKNOWN_QR = 'UNKNOWN_QR',
  REVOKED_QR = 'REVOKED_QR',
  BLOCKED_QR = 'BLOCKED_QR',
  EXPIRED = 'EXPIRED',
  RECALLED = 'RECALLED',
  SUSPENDED = 'SUSPENDED',
  UNABLE_TO_VERIFY = 'UNABLE_TO_VERIFY',
}

export enum FraudSignalType {
  HIGH_SCAN_FREQUENCY = 'HIGH_SCAN_FREQUENCY',
  GEOGRAPHIC_ANOMALY = 'GEOGRAPHIC_ANOMALY',
  IMPOSSIBLE_TRAVEL = 'IMPOSSIBLE_TRAVEL',
  EXCESSIVE_QR_REUSE = 'EXCESSIVE_QR_REUSE',
  SERIAL_REUSE = 'SERIAL_REUSE',
  AI_PHYSICAL_MISMATCH = 'AI_PHYSICAL_MISMATCH',
  PACKAGING_MISMATCH = 'PACKAGING_MISMATCH',
  CONSUMER_REPORT = 'CONSUMER_REPORT',
}

export enum AiMode {
  AI_DISABLED = 'AI_DISABLED',
  AI_OPTIONAL = 'AI_OPTIONAL',
  AI_REQUIRED = 'AI_REQUIRED',
}

export enum AiJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  IMAGE_NOT_CLEAR = 'IMAGE_NOT_CLEAR',
  AI_NOT_CONFIGURED = 'AI_NOT_CONFIGURED',
  AI_UNAVAILABLE = 'AI_UNAVAILABLE',
}

export enum InvestigationStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
  CONFIRMED_COUNTERFEIT = 'CONFIRMED_COUNTERFEIT',
  RESOLVED = 'RESOLVED',
}

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  MANUFACTURER_ADMIN = 'MANUFACTURER_ADMIN',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  FRAUD_INVESTIGATOR = 'FRAUD_INVESTIGATOR',
  ANALYST = 'ANALYST',
  READ_ONLY = 'READ_ONLY',
}

export enum ImageViewAngle {
  FRONT = 'FRONT',
  BACK = 'BACK',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  TOP = 'TOP',
  BOTTOM = 'BOTTOM',
  ADDITIONAL = 'ADDITIONAL',
}

export enum LocationSource {
  GPS = 'GPS',
  IP = 'IP',
  NETWORK = 'NETWORK',
  MANUAL = 'MANUAL',
  UNKNOWN = 'UNKNOWN',
}

export enum QrOutputFormat {
  PNG = 'PNG',
  SVG = 'SVG',
  PDF = 'PDF',
}

export enum BulkJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
